[package]
name = "rusticrayz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Force dynamic linking, which improves iterative compile times
dynamic = ["link-dynamic"]

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
pollster = "0.3"
wgpu = "0.17"
winit = "0.28"
egui = "0.23"
egui-wgpu = "0.23"
egui-winit = "0.23"

link-dynamic = { path = "link-dynamic", version = "0.1", optional = true }
