[package]
name = "link-dynamic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
wgpu = "0.17"
winit = "0.28"
egui = "0.23"
